spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url: http://discovery:8080/eureka/
