version: "2"

services:

  ingredient:
    build: ingredient
    ports:
     - "9010:8080"
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"

  ingredient_mongo:
    container_name: ingredient_mongo
    image: mongo:4.0.5
    ports:
    - "9011:27017"
    volumes:
    - ./containerdata/mongo:/data