spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://discovery:8080/eureka/
    register-with-eureka: false
    fetch-registry: false